### ISSUE TITLE
Feature Request: Add rule for reg.present to use integers for REG_DWORD

### ISSUE THREAD

**Issue by flassman** [warpnet/salt-lint#110]
reg.present can take strings as input for REG_DWORD values, however the state then does not detect if the value is already set correctly, see https://github.com/saltstack/salt/issues/55284
```
HKEY_LOCAL_MACHINE:
  reg.present:
    - vname: MyTest
    - vtype: REG_DWORD
    - vdata: '00000001'
```

so to be in the safe side, the REG_DWORD should be used with integers in vdata like this:
```
HKEY_LOCAL_MACHINE:
  reg.present:
    - vname: MyTest
    - vtype: REG_DWORD
    - vdata: 1
```
