### ISSUE TITLE
False positive for content -> contents (218)

### ISSUE THREAD

**Issue by hafkensite** [warpnet/salt-lint#252]
**Describe the bug**
The new [TypoContentsRule](https://github.com/warpnet/salt-lint/blob/v0.6.0/saltlint/rules/TypoContentsRule.py) rule assumes all instances of 'content' should be 'content**s**', but for `file.line` the parameter is actually called 'content'. 

**To Reproduce**
Run version 0.6.0 on code like this:
```yaml
gitlab-runner-listen-address:
  file.line:
    - name: /etc/gitlab-runner/config.toml
    - content: 'listen_address = "0.0.0.0:9252"'
    - match: '^listen_address = .*'
```

**Expected behavior**
The 218 rule only matches cases where its actually a typo.

**Desktop (please complete the following information):**
- OS: Arch
- Version 0.6.0
