### ISSUE TITLE
Add check for proper nested dict indentation

### ISSUE THREAD

**Issue by sblaisot** [warpnet/salt-lint#282]
**Is your feature request related to a problem? Please describe.**
Nested dicts should be over-indented (this is required by yaml). See https://docs.saltproject.io/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#nested-dictionaries

We should add a check in salt-lint to ensure proper over-indentation of `context` or `defaults` elements or `data` parameter of `debconf.set` (and maybe others I'm not aware of)

See `Note` in https://docs.saltproject.io/en/latest/ref/states/all/salt.states.debconfmod.html#available-functions

**Describe the solution you'd like**

```
ID:
  file.managed:
    - source: salt://path/to/source
    - template: jinja
    - context:
      somevar: somevalue
```

should fail the new test while

```
ID:
  file.managed:
    - source: salt://path/to/source
    - template: jinja
    - context:
        somevar: somevalue
```

should success
