### ISSUE TITLE
Check in the names argument  is a list in the pkg.installed module

### ISSUE THREAD

**Issue by roaldnefs** [warpnet/salt-lint#314]
When using the `pkg.installed` module it's possible to installed multiple packages by providing a list, e.g.:

```yaml
example_packages:
  pkg.installed:
    - names: ['package', 'other_package'] 
```

When the code is updated to only install a single package this can be rewritten to the following:

```yaml
example_packages:
  pkg.installed:
    - name: package
```

But when the `names` argument is kept it will result in the error `The 'names' argument in state 'example_packages` in SLS 'example' needs to be formed as a list`:

```yaml
example_packages:
  pkg.installed:
    - names: package
```

This can be prevented by checking if the `names` argument in the `pkg.installed` modules actually contains a list.
